# Generated by Django 5.0.1 on 2024-01-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ispot',
            fields=[
                ('ispot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ispot_name', models.CharField(max_length=50)),
                ('icategory', models.CharField(choices=[('india', 'india'), ('international', 'innternational')], max_length=100)),
                ('idesc', models.CharField(max_length=255)),
                ('iprice', models.IntegerField()),
                ('iimage', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Nspot',
            fields=[
                ('nspot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nspot_name', models.CharField(max_length=50)),
                ('ncategory', models.CharField(choices=[('india', 'india'), ('international', 'innternational')], max_length=100)),
                ('ndesc', models.CharField(max_length=255)),
                ('nprice', models.IntegerField()),
                ('nimage', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
