# Generated by Django 4.2.9 on 2024-02-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelloApp', '0002_pessanger_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pessanger_detail',
        ),
    ]
