# Generated by Django 4.2.9 on 2024-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelloApp', '0003_delete_pessanger_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
